<?php

namespace Quiz\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestResultRepository extends EntityRepository
{
}
