_index:
    path: /
    defaults: {_controller: QuizCoreBundle:Default:index}

_test:
    path: /test
    defaults: {_controller: QuizCoreBundle:Default:test}

_teacher:
    path: /teacher
    defaults: {_controller: QuizCoreBundle:Default:teacher}