_index:
    path: /
    defaults: {_controller: QuizCoreBundle:Default:index}

_registration_check_email:
    path: /register/checkEmail
    defaults: {_controller: QuizCoreBundle:Registration:emailAvailable, email: null}
    requirements:
        _method: POST

_registration_check_username:
    path: /register/checkUsername
    defaults: {_controller: QuizCoreBundle:Registration:usernameAvailable, username: null}
    requirements:
        _method: POST


_registration_check_registry_number:
    path: /register/checkRegistryNumber
    defaults: {_controller: QuizCoreBundle:Registration:registryNumberAvailable, registryNumber: null}
    requirements:
        _method: POST

_quiz_page:
        path: /quiz/{id}
        defaults: {_controller: QuizCoreBundle:Quiz:index, id: 0}
        requirements:
            page: \d+
            _method: GET

_start_quiz:
            path: /quiz/{id}/start
            defaults: {_controller: QuizCoreBundle:Quiz:start, id: 1}
            requirements:
              _method: GET

_submit_quiz:
        path: /quiz/{id}/submit
        defaults: {_controller: QuizCoreBundle:Quiz:submitQuiz}
        requirements:
          _method: POST

_edit_quiz:
          path: /quiz/edit/{id}
          defaults: {_controller: QuizCoreBundle:Admin:editOrCreateQuiz, id: null}

_new_quiz:
          path: /createQuiz
          defaults: {_controller: QuizCoreBundle:Admin:editOrCreateQuiz, id: null}
