_index:
    path: /
    defaults: {_controller: QuizCoreBundle:Default:index}

_test:
    path: /test
    defaults: {_controller: QuizCoreBundle:Default:test}

_teacher:
    path: /teacher
    defaults: {_controller: QuizCoreBundle:Default:teacher}

_registration:
    path: /register/checkEmail
    defaults: {_controller: QuizCoreBundle:Registration:emailAvailable, email: null}
    requirements:
        _method: POST
