services:
    quiz_user.registration.form.type:
      class: Quiz\CoreBundle\Form\Type\RegistrationFormType
      tags:
        - {name: form.type, alias: quiz_user_registration}



    fos_user.doctrine_registry:
        alias: doctrine




    app.twig_extension:
           class: Quiz\CoreBundle\Twig\GetQuizTypeName
           public: false
           tags:
               - { name: twig.extension }

    quiz_user.group_set:
      class: %quiz_user.group_set.class%
      arguments: [@fos_user.user_manager, @doctrine.orm.entity_manager]
      tags:
        - { name: kernel.event_subscriber }
    ap_user.edit.form.type:
            class: Quiz\CoreBundle\Form\Type\EditFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: ap_edit_profile }